# Generated by Django 4.2.10 on 2026-06-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('save_dir', models.CharField(default='binary_cnn/saved_models', max_length=100)),
                ('static_dir_path', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Untrained', 'Untrained'), ('Training', 'Training'), ('Trained', 'Trained'), ('Error', 'Error')], default='Untrained', max_length=9)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('save_dir', models.FileField(upload_to='binary_cnn/datasets/tmp')),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Text', 'Text'), ('Audio', 'Audio'), ('Video', 'Video')], max_length=10)),
                ('category', models.CharField(choices=[('Training', 'Training'), ('Validation', 'Validation'), ('Classify', 'Classify'), ('Other', 'Other')], max_length=10)),
                ('input_shape', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('class_labels', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(upload_to='binary_cnn/static/')),
                ('is_classified', models.BooleanField(default=False)),
                ('date_classified', models.DateTimeField(auto_now=True)),
                ('img_classification', models.CharField(blank=True, max_length=100)),
                ('prob_classification', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('model_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('learning_rate', models.DecimalField(decimal_places=8, default=0.001, max_digits=10)),
                ('minimum_accuracy', models.DecimalField(decimal_places=8, default=0.99, max_digits=10)),
                ('num_of_batches', models.IntegerField(default=8)),
                ('num_of_epochs', models.IntegerField(default=15)),
                ('binary_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='binary_cnn.binarymodel')),
                ('training_ds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_training_ds', to='binary_cnn.dataset')),
                ('validation_ds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_validation_ds', to='binary_cnn.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actual_accuracy', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('actual_val_accuracy', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('actual_epochs', models.IntegerField(default=0)),
                ('precision', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('recall', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('f1_score', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('training_time_dhms', models.CharField(blank=True, max_length=100)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='binary_cnn.trainconfig')),
            ],
        ),
    ]
